## Naives Bayes Classification -  Mushroom Classification using Naives Bayes Model

### Loading the Dataset

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv('mushroom.csv')
df.head(n=10)

type cap_shape cap_surface cap_color bruises odor gill_attachment  \
0    p         x           s         n       t    p               f   
1    e         x           s         y       t    a               f   
2    e         b           s         w       t    l               f   
3    p         x           y         w       t    p               f   
4    e         x           s         g       f    n               f   
5    e         x           y         y       t    a               f   
6    e         b           s         w       t    a               f   
7    e         b           y         w       t    l               f   
8    p         x           y         w       t    p               f   
9    e         b           s         y       t    a               f   

  gill_spacing gill_size gill_color   ...   stalk_surface_below_ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   
5            c         b          n   ...                          s   
6            c         b          g   ...                          s   
7            c         b          n   ...                          s   
8            c         n          p   ...                          s   
9            c         b          g   ...                          s   

  stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   
5                      w                      w         p          w   
6                      w                      w         p          w   
7                      w                      w         p          w   
8                      w                      w         p          w   
9                      w                      w         p          w   

  ring_number ring_type spore_print_color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  
5           o         p                 k          n       g  
6           o         p                 k          n       m  
7           o         p                 n          s       m  
8           o         p                 k          v       g  
9           o         p                 k          s       m  

[10 rows x 23 columns]

### Encoding the categorical data into numerical data

In [5]:
le = LabelEncoder()
## applies transformation on each column
# it basically applies encoding to each column from categorical data, by default in pandas apply(), its axis is 0, its means it applies on each columns
#fit_transform applies encoding or label on array
ds = df.apply(le.fit_transform)
# ds has integer label instead of categorical label
type(ds)
# it is again pandas dataframe
ds.head(n=10)


type  cap_shape  cap_surface  cap_color  bruises  odor  gill_attachment  \
0     1          5            2          4        1     6                1   
1     0          5            2          9        1     0                1   
2     0          0            2          8        1     3                1   
3     1          5            3          8        1     6                1   
4     0          5            2          3        0     5                1   
5     0          5            3          9        1     0                1   
6     0          0            2          8        1     0                1   
7     0          0            3          8        1     3                1   
8     1          5            3          8        1     6                1   
9     0          0            2          9        1     0                1   

   gill_spacing  gill_size  gill_color   ...     stalk_surface_below_ring  \
0             0          1           4   ...                            2   
1             0          0           4   ...                            2   
2             0          0           5   ...                            2   
3             0          1           5   ...                            2   
4             1          0           4   ...                            2   
5             0          0           5   ...                            2   
6             0          0           2   ...                            2   
7             0          0           5   ...                            2   
8             0          1           7   ...                            2   
9             0          0           2   ...                            2   

   stalk_color_above_ring  stalk_color_below_ring  veil_type  veil_color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   
5                       7                       7          0           2   
6                       7                       7          0           2   
7                       7                       7          0           2   
8                       7                       7          0           2   
9                       7                       7          0           2   

   ring_number  ring_type  spore_print_color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  
5            1          4                  2           2        1  
6            1          4                  2           2        3  
7            1          4                  3           3        3  
8            1          4                  2           4        1  
9            1          4                  2           3        3  

[10 rows x 23 columns]

In [6]:
# now we are done to convert it into numpy array,
data = ds.values # ---> we are not giving brackets because, it is property not function
print(data.shape)
print(type(data))
print(data[:5,:])
#now data is ready, we are ready for further computation
# if you observe carefully, you will see, the zeroth column of dataframe is y feature and rest are x features now split them
data_x = data[:,1:]
data_y = data[:,0]

(8124, 23)
<class 'numpy.ndarray'>
[[1 5 2 4 1 6 1 0 1 4 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 9 1 0 1 0 0 4 0 2 2 2 7 7 0 2 1 4 3 2 1]
 [0 0 2 8 1 3 1 0 0 5 0 2 2 2 7 7 0 2 1 4 3 2 3]
 [1 5 3 8 1 6 1 0 1 5 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 3 0 5 1 1 0 4 1 3 2 2 7 7 0 2 1 0 3 0 1]]


### Break the data into train and test

In [7]:
x_train,x_test,y_train,y_test = train_test_split(data_x,data_y,test_size = 0.2)


In [8]:
print(x_train.shape,x_test.shape)
print(y_train.shape,y_test.shape)

(6499, 22) (1625, 22)
(6499,) (1625,)


In [9]:
### to check how many category or classes available for mushroom
np.unique(y_train)

array([0, 1])

In [10]:
#so u can see there are two types of mushroom
# there is also a method available in sklearn to inverse the numerical label in character labels
# that is inverse_transform , for this check documentation

### Building Our Classifier

In [11]:
# here is shortcut to count labels
a  =np.array([1,1,1,0,0,0])
np.sum(a==1)
# its returns a value which mention total number of labels habing value one

3

In [13]:
def prior_prob(y_train,label):
    total_examples = y_train.shape[0]
    class_examples = np.sum(y_train==label)
    
    return (class_examples)/float(total_examples)

In [26]:
# in condtional probabilty---> first we short out the class which we want, no. of outcomes from all outcomes having class X
# then after this filtered outcome we find in how many outcomes having label Y 
def cond_prob(x_train,y_train,feature_col,feature_val,label):
    x_filtered = x_train[y_train==label]
    numerator = np.sum(x_filtered[:,feature_col]==feature_val)
    denominator = np.sum(y_train==label)
    
    return numerator/float(denominator)

In [27]:
### computing posterior probability

In [28]:
def predict(x_train,y_train,xtest):
    classes = np.unique(y_train)
    n_features = x_train.shape[1]
    
    post_prob = [] #list of prob for all the classes and given a single testing point
    for label in classes:
        likelihood = 1.0
        for f in range(n_features):
            cond = cond_prob(x_train,y_train,f,xtest[f],label)
            likelihood*=cond
            
        prior = prior_prob(y_train,label)
        
        post = likelihood*prior #--> neglecting marginal probability
        post_prob.append(post)
    pred = np.argmax(post_prob)
    return pred
            

In [29]:
output = predict(x_train,y_train,x_test[1])
print(output)
print(y_test[1])

1
1


In [30]:
def score(x_train, y_train,x_test,y_test):
    pred = []
    for i in range(x_test.shape[0]):
        pred_label = predict(x_train,y_train,x_test[i])
        pred.append(pred_label)
        
    pred = np.array(pred)
    acc = np.sum(pred==y_test)/y_test.shape[0]
    return acc

In [31]:
print(score(x_train,y_train,x_test,y_test))

0.9969230769230769
